"""password length from 100 to 200

Revision ID: e8735a690257
Revises: 0bd19d8d357e
Create Date: 2023-10-25 00:24:56.608198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8735a690257'
down_revision: Union[str, None] = '0bd19d8d357e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('prod_status', sa.String(length=100), nullable=True))
    op.drop_column('products', 'pod_status')
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('products', sa.Column('pod_status', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('products', 'prod_status')
    # ### end Alembic commands ###
